package com.sudh.accord.ui.theme

import androidx.compose.ui.graphics.Color

// ── Accord brand palette ──────────────────────────────────────────────────
// Seed: #0D9488 (the teal already used by LoginScreen/OnboardingScreen).
// Roles below follow Material 3's tonal palette structure, hand-tuned around
// that seed so every screen matches the teal identity instead of the
// leftover Android Studio default (Purple 40/80) or per-device dynamic color.

// Light scheme
val md_theme_light_primary = Color(0xFF0D9488)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA6F2E4)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4A635F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E2)
val md_theme_light_onSecondaryContainer = Color(0xFF051F1C)
val md_theme_light_tertiary = Color(0xFFB4530A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC2)
val md_theme_light_onTertiaryContainer = Color(0xFF3A1A00)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFAFCFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFCFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4947)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_outlineVariant = Color(0xFFBFC9C5)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF3F6F4)
val md_theme_light_surfaceContainer = Color(0xFFEDF1EE)
val md_theme_light_surfaceContainerHigh = Color(0xFFE7EBE9)
val md_theme_light_surfaceContainerHighest = Color(0xFFE1E5E3)

// Dark scheme
val md_theme_dark_primary = Color(0xFF5BDBC9)
val md_theme_dark_onPrimary = Color(0xFF00382F)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF7BF8E4)
val md_theme_dark_secondary = Color(0xFFB0CCC6)
val md_theme_dark_onSecondary = Color(0xFF1B3532)
val md_theme_dark_secondaryContainer = Color(0xFF324B47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E2)
val md_theme_dark_tertiary = Color(0xFFFFB77C)
val md_theme_dark_onTertiary = Color(0xFF4C2700)
val md_theme_dark_tertiaryContainer = Color(0xFF6C3900)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC2)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF0F1413)
val md_theme_dark_onBackground = Color(0xFFDEE4E1)
val md_theme_dark_surface = Color(0xFF0F1413)
val md_theme_dark_onSurface = Color(0xFFDEE4E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4947)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C5)
val md_theme_dark_outline = Color(0xFF899391)
val md_theme_dark_outlineVariant = Color(0xFF3F4947)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0A0F0E)
val md_theme_dark_surfaceContainerLow = Color(0xFF171C1B)
val md_theme_dark_surfaceContainer = Color(0xFF1B201F)
val md_theme_dark_surfaceContainerHigh = Color(0xFF262B2A)
val md_theme_dark_surfaceContainerHighest = Color(0xFF313634)